# docker compose -f docker-compose.dev.yaml up --build

services:
  database:
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
       - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/WeddingConfirmationApp
      dockerfile: WeddingConfirmationApp.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: Host=database;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}
      DefaultAdmin__Username: ${DefaultAdminUsername}
      DefaultAdmin__Password: ${DefaultAdminPassword}
      Jwt__Key: ${JwtKey}
      Jwt__Issuer: ${JwtIssuer}
      Jwt__Audience: ${JwtAudience}
      AllowedOrigins: ${AllowedOrigins}
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  postgres_data: